severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

enableAllRules = true

[rule.line-length-limit]
  arguments = [100]

[rule.add-constant]
Disabled = true

[rule.package-comments]
Disabled = true

[rule.exported]
Disabled = true

[rule.unhandled-error]
arguments = ["fmt.Print.*"]

[rule.cognitive-complexity]
  arguments = [10]
