severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 2

enableAllRules = true

[rule.line-length-limit]
  Arguments = [100]

[rule.add-constant]
  Disabled = true

[rule.package-comments]
  Disabled = true

[rule.exported]
  Disabled = true

[rule.unhandled-error]
  Arguments = ["fmt\\.Print\\w*"]
  Exclude = ["TEST"]

[rule.cognitive-complexity]
  Arguments = [10]

[rule.dot-imports]
  Arguments = [{ allowedPackages = ["github.com/onsi/ginkgo/v2","github.com/onsi/gomega"] }]

[rule.blank-imports]
  Exclude = ["tools.go"]
