severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 2

enableAllRules = true

[rule.line-length-limit]
  arguments = [100]

[rule.add-constant]
Disabled = true

[rule.package-comments]
Disabled = true

[rule.exported]
Disabled = true

[rule.unhandled-error]
arguments = ["fmt\\.Print\\w*"]

[rule.cognitive-complexity]
  arguments = [10]
