name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: go build -v -o nst
    - uses: actions/upload-artifact@v4
      with:
        name: nst
        path: nst
        if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: go run github.com/onsi/ginkgo/v2/ginkgo run -r -p --coverprofile=coverprofile.out
    - run: go tool cover -func=coverprofile.out
    - run: go tool cover -func=coverprofile.out -o coverage.txt
    - run: go tool cover -html=coverprofile.out -o coverage.html
    - uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: |
          coverprofile.out
          coverage.txt
          coverage.html
        if-no-files-found: error

  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: go vet ./...

  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: go mod verify

  gofmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: diff -u <(echo -n) <(gofmt -d ./)

  revive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: go run github.com/mgechev/revive -config .revive.toml $(git ls-files | grep '\.go$')
