name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: go build -v -o bin/nst
    - uses: actions/upload-artifact@v4
      with:
        name: bin
        if-no-files-found: error
        path: bin/nst

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: go run github.com/onsi/ginkgo/v2/ginkgo run -r -p --coverprofile=coverprofile.out
    - run: go tool cover -func=coverprofile.out
    - run: go tool cover -func=coverprofile.out -o coverage.txt
    - run: go tool cover -html=coverprofile.out -o coverage.html
    - uses: actions/upload-artifact@v4
      with:
        name: coverage
        if-no-files-found: error
        path: |
          coverprofile.out
          coverage.txt
          coverage.html

  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: go vet ./...

  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: go mod verify

  gofmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: diff -u <(echo -n) <(gofmt -d ./)

  revive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'
    - run: go run github.com/mgechev/revive -config .revive.toml ./...
